config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root to: 'pages#home'

  resources :users do
    resources :occurrences, only: %i[new create]
  end
  resources :occurrences, only: %i[index show]

  resources :members do
    member do
      delete :delete_image_attachment
    end
    resources :crews, only: %i[new create index]
  end

  resources :ships do
    member do
      delete :delete_image_attachment
    end
    resources :crews, only: %i[new create index]
  end

  resources :crews, only: %i[index show edit update delete]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/crew.rb
class Crew < ApplicationRecord
  belongs_to :members
  belongs_to :ships
end

app/models/member.rb
class Member < ApplicationRecord
end

app/models/occurrence.rb
class Occurrence < ApplicationRecord
  belongs_to :user
  belongs_to :ship

  # include PgSearch::Model
  # pg_search_scope :search_by_origin_and_destination,
  #   against: %i[ship_origin ship_destination],
  #   using: {
  #     tsearch: { prefix: true }
  #   }
  # pg_search_scope :search_by_ship,
  #   associated_against: {
  #     ship: %i[name registration registration_port]
  #   },
  #   using: {
  #     tsearch: { prefix: true }
  #   }
end

app/models/ship.rb
class Ship < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/crews_controller.rb
class CrewsController < ApplicationController
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
end

app/controllers/occurrences_controller.rb
class OccurrencesController < ApplicationController

  def index
    if params[:query_ship]
      @occurrences = Occurrence.search_by_ship(params[:query_ship])
    else
      @occurrences = Occurrence.all
    end

    if !@occurrences.nil?
     @markers = @occurrences.map do |occurrence|
       {
         lat: occurrence.latitude,
         lng: occurrence.longitude,
         #info_window: render_to_string(partial: "info_window", locals: { occurrence: occurrence })
       }
     end
    end
  end

  def show
    @occurrence = Occurrence.find(params[:id])
  end

  def new
    @occurrence = Occurrence.new
  end

  def create
    @occurrence = Occurrence.new(occurrence_params)
    @occurrence.user = current_user
    if @occurrence.save
      redirect_to occurrences_path, notice: 'Occurrence was successfully created!'
    else
      render :new
    end
  end

  private
  def occurrence_params
    params.require(:occurrence).permit(
      :ship_id, :latitude, :longitude, :date, :time, :ship_origin, :ship_destination, :user_id, :description
    )
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]

  def home
  end
end

app/controllers/ships_controller.rb
class ShipsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Base de Dados - NEPOM</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <div class="container">
      <div class="row justify-content-center">
        <div class="mt-4 col-12 col-lg-6">
          <%= yield %>
        </div>
      </div>
    </div>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/occurrences/index.html.erb
<h2 class="text-center pb-2"><i class="fas fa-paste text-secondary"></i> Ocorrências</h2>

<%= form_tag occurrences_path, method: :get do %>
    Pesquisa por embarcação:
    <%= text_field_tag :query_ship,
      params[:query_ship],
      class: "form-control",
      placeholder: "Nome, registro ou porto de registro"
    %>
     <div class="text-center p-4">
      <%= submit_tag "Pesquisar", class: "btn btn-primary text-white mr-2 mb-2" %>
      <%= link_to "Limpar Pesquisa", request.path, class:"cancel-button btn btn-primary text-white mb-2 mr-2" %>
      <%= link_to 'Criar ocorrência', new_user_occurrence_path(current_user), class:"btn btn-info mr-2 mb-2" %>
    </div>
<% end %>

<div class= "mb-2" id="map"
     style="width: 100%; height: 350px;"
     data-markers="<%= @markers.to_json %>"
     data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>

<div class="text-center p-4">
  <%# <%= link_to 'Criar ocorrência', new_user_occurrence_path(current_user), class:"btn btn-primary text-white mt-2 mb-2" %>
  <%= link_to 'Voltar', :back, class:"btn btn-info mt-2 ml-2 mb-2" %>
</div>

<h3 class="text-center mt-2 pb-2 mb-3"><i class="fas fa-paste text-secondary"></i> Últimas Ocorrências</h3>

<% @occurrences.each do |occurrence| %>
  <div class="card p-3 mb-3">
    <div class="d-flex justify-content-between text-dark">
      <h5> <strong>#</strong><%=occurrence.ship.name%> </h5>
      <h5> <strong><%#= occurrence.date.strftime("%d/%m/%Y")%></strong></h5>
    </div>
    <%=link_to "Detalhes", occurrence_path(occurrence), class: "btn btn-primary text-white m-4"%>
  </div>
<% end %>

app/views/occurrences/new.html.erb
<h2 class="page-title mb-2 text-center"><i class="fa-solid fa-location-dot text-secondary"></i> Criar ocorrência</h2>
<p id="position" class="text-center"></p>

<script src='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.js'></script>
<link href='https://api.mapbox.com/mapbox-gl-js/v2.7.0/mapbox-gl.css' rel='stylesheet'/>

<div id="map-new-point" class="mb-4"
     style="width: 100%; height: 300px;"> </div>

<%= simple_form_for([ current_user, @occurrence ], remote: true) do |f| %>
  <div id="new-form">
    <%#= f.input :latitude, label: 'Latitude', required: true %>
    <%#= f.input :longitude, label: 'Longitude', required: true %>
    <%= f.input :occurrence_date, label: 'Data', :order => [:day, :month, :year], required: true, as: :date  %>
    <%= f.input :occurrence_time, label: 'Hora', as: :string, input_html: { value: Time.now.strftime("%H:%M:%S") }, as: :time %>
    <%= f.input :occurrence_type, label: 'Tipo de ocorrência', as: :string, required: true %>
    <%= f.input :ship_origin, label: 'Origem', as: :string, required: true %>
    <%= f.input :ship_destination, label: 'Destino', as: :string, required: true %>
  </div>

  <%= f.button :submit, "Criar ocorrência", class:"btn btn-primary mb-2 mr-2" %>
  <%= link_to "Voltar", :back, class:"btn btn-info mb-2" %>
<% end %>

app/views/pages/home.html.erb
<h2 class="text-center"><i class="fas fa-check-circle text-secondary"></i> Escolha uma opção</h2>

<div>
  <div class="buttons text-center pt-2">
    <div class="button pt-4">
      <%=link_to "Ocorrências", occurrences_path, class: "btn btn-primary text-white w-50"%>
    </div>

    <div class="button pt-4">
      <%=link_to "Embarcações", ships_path, class: "btn btn-primary text-white w-50"%>
    </div>

    <div class="button pt-4">
      <%=link_to "Tripulantes", members_path, class: "btn btn-primary text-white w-50"%>
    </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/lcpret/base-de-dados-nepom"><i class="fab fa-github"></i></a>
  </div>
  <div class="footer-copyright">
    NEPOM Dados <i class="far fa-registered"></i>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon m-6">

  <div class="logo d-flex justify-content-between">
    <div class="xepa text-left d-flex align-items-center">
      <a href="<%=root_path%>">
        <%= image_tag "logo_pf.svg",size:70%> </a>
        <h5 class="app-name"><strong> NEPOM Dados</strong></h5>

    </div>
  </div>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item active d-flex justify-content-center">
         <%= link_to "Home", root_path, class: "nav-link" %>
      </li>
      <% if user_signed_in? %>
        <li class="nav-item dropdown text-center">
          <%= image_tag "user_icon.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Meu perfil", edit_user_registration_path, class: "dropdown-item" %>
            <%= link_to "Sair", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item text-center">
          <%= link_to "Entrar", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>